[16기 장진욱] AGEOSTE-backend cartview
wecode-bootcamp-korea/AGEOSTE-backend pull request #15
Opened 2021-01-20 01:10 UTC by jinukix

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- cartview(장바구니) 작성
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항
- 트랜잭션 기능을 사용해보고싶었는데 굳이 써야하나? 라는 생각이드네요.. 결제할때 사용해야 할까요??

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-20 02:13 UTC, jamessoun93 requested changes

2021-01-20 02:13 UTC, jamessoun93 commented on order/views.py
> +            carts = request.user.carts.all().select_related("product", "size", "color", "thumbnail")
```suggestion
            carts = request.user.carts.select_related("product", "size", "color", "thumbnail")
```

2021-01-20 02:13 UTC, jamessoun93 commented on order/views.py
> +        except Cart.DoesNotExist:
음 DoesNotExist 에러가 발생할까요?

2021-01-20 02:13 UTC, jamessoun93 commented on order/views.py
> +            image      = Image.objects.get(image_url=data['image']) # 프론트에서 이미지url보내는 방향으로 이야기, or product -> productcolorimages(product, color로 검색) -> image
이 부분들은 전부 id 로 받으면 편할 것 같은데, 그렇게 하기 힘든 이유가 있을까요?

2021-01-20 02:13 UTC, jamessoun93 commented on order/views.py
> +                return JsonResponse({"MESSAGE" : "Create Cart"}, status=201)
`get_or_create()` 를 사용해보세요 :)

2021-01-20 02:13 UTC, jamessoun93 commented on order/views.py
> +            cart.count = data['cart_id']
cart.count 를 cart_id 로 업데이트 해주시는 부분이 잘 이해가 안가네요. 설명해주실 수 있을까요?

2021-01-20 02:47 UTC, jinukix commented on order/views.py
> +            carts = request.user.carts.all().select_related("product", "size", "color", "thumbnail")
앗 그러네요 수정했습니다!

2021-01-20 02:47 UTC, jinukix commented on order/views.py
> +        except Cart.DoesNotExist:
발생하지않네요...

2021-01-20 02:52 UTC, jinukix commented on order/views.py
> +            cart.count = data['cart_id']
cart.count = data['count'] 였는데 잘못들어간거같네요..

2021-01-20 03:23 UTC, jamessoun93 commented on order/views.py
> +        except Cart.DoesNotExist:
넵. DoesNotExist 에러가 정확히 언제 어떻게 발생할 수 있는지에 대해 알아보시고 답글로 남겨주세요.

2021-01-20 04:33 UTC, jinukix commented on order/views.py
> +            image      = Image.objects.get(image_url=data['image']) # 프론트에서 이미지url보내는 방향으로 이야기, or product -> productcolorimages(product, color로 검색) -> image
```
"product": {
        "name": "티셔츠",
        "code": "AGSTE041",
        "description": "상품설명",
        "price": "90000.00",
        "sail_percent": 30,
        "review_score_avg": 3,
        "hashtags": [
            ...
        ],
        "sizes": [
            "S",
            "M",
            "L",
        ],
        "color_images": [
            {
                "color_name": "WHITE",
                "img": [
                    "img1",
                    "img2",
                    "img3",
                    "img4",
                ],
                "color_name": "RED",
                "img": [
                    "img1",
                    "img2",
                    "img3",
                    "img4",
                ]
            },
        ...
```

저희 상품 디테일 뷰가 이런식으로 들어가는데, 이데이터를 가지고 프론트에서 사이즈,색깔,이미지를 id값을 얻어오는게 힘들다고 판단했습니다.

2021-01-20 04:38 UTC, jinukix commented on order/views.py
> +        except Cart.DoesNotExist:
objects.get을 했을때 데이터가 존재하지않으면 DoesNotExist에러가 발생합니다.

2021-01-20 08:05 UTC, jamessoun93 commented on order/views.py
> +            image      = Image.objects.get(image_url=data['image']) # 프론트에서 이미지url보내는 방향으로 이야기, or product -> productcolorimages(product, color로 검색) -> image
리스트의 각 아이템에 우리 데이터베이스에 들어가는 각 객체의 id 가 포함되게끔 해서 보내주시면 해결이 되겠네요.

2021-01-20 09:14 UTC, jinukix commented on order/views.py
> +            image      = Image.objects.get(image_url=data['image']) # 프론트에서 이미지url보내는 방향으로 이야기, or product -> productcolorimages(product, color로 검색) -> image
겨우 해결했습니다..

2021-01-21 01:26 UTC, jamessoun93 commented
LGTM

2021-01-21 01:26 UTC, merged