[16기 최수아] AGEOSTE-backend Add : PaymentView
wecode-bootcamp-korea/AGEOSTE-backend pull request #16
Opened 2021-01-20 06:16 UTC by sue517

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- payment view 생성 (결제 관련 부분은 X... 장바구니에서 넘어와서 멤버십 discount, coupon discount 적용하는 부분 까지만 만들었습니다)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-20 08:14 UTC, jamessoun93 requested changes

2021-01-20 08:14 UTC, jamessoun93 commented on order/views.py
> +
order_address 도 None 인 경우 어떻게 처리가 되어야 할까요? 지금은 그대로 NULL 이 들어가게끔 되어있네요.

2021-01-20 08:14 UTC, jamessoun93 commented on order/views.py
> +            coupons = UserCoupon.objects.filter(user=user).select_related('user', 'coupon')
- select_related 어제 이해 잘 안되신다고 하셨으니 여기서 select_related 가 무엇을 해주며, 어떤 이점이 있어서 사용하셨는지, 그리고 확인은 어떻게 해보셨는지 답글로 설명해주세요 :)
- 그리고 아래 carts_list 리스트 컴프리헨션을 보니 carts 에서 user 를 굳이 JOIN 해올 필요가 없어보이네요.

2021-01-20 08:14 UTC, jamessoun93 commented on order/views.py
> +        except CartDoesNotExist:
삐빅 🚨 확인부탁드립니다.

2021-01-20 08:14 UTC, jamessoun93 commented on user/views.py
> +        coupons = UserCoupon.objects.filter(user=user).select_related('user', 'coupon')
user 까지 JOIN 해올 필요가 있나요?

2021-01-20 08:44 UTC, sue517 commented on order/views.py
> +            coupons = UserCoupon.objects.filter(user=user).select_related('user', 'coupon')
- cart 에서 select_related 를 사용한 이유는 cart 가 fk 를 갖고 있는 정참조라고 생각해서 사용했습니다. 저희 모델을 보시면 product 관련 키(상품 이름, 가격(을 보니까 빼먹었네요... 다음 커밋때는 추가하겠습니다), 할인율)는 product 테이블에서, size 는 size table 에서, color 는 color 테이블에서 가져와야 할거 같아 해당 테이블들을 미리 불러오도록 하였습니다. 사실 아직 select 를 써야하는지 prefetch 를 써야하는지 하는 부분이나 사용해도 적용이 가능한지의 부분등이 모델을 켜두지 않으면 긴가민가하게 그려져서ㅠㅠ shell 에 다 찍어보고... 값 뽑아보고 사용한거라 완벽하게 이해했다고는 못하겠네요ㅠㅠ 사용할 수 있는 한 자주 사용하려 노력해보려 합니닷...😣

- 오옹 user 부분 빼도 되는거 확인했습니다 감사합니다!

2021-01-20 08:44 UTC, sue517 commented on order/views.py
> +        except CartDoesNotExist:
확인했습니당 🚒 ,,,,,

2021-01-20 08:44 UTC, sue517 commented on user/views.py
> +        coupons = UserCoupon.objects.filter(user=user).select_related('user', 'coupon')
확인했습니다 감사합니다 @_@

2021-01-20 08:44 UTC, sue517 commented on order/views.py
> +
앗... 실제로 구현되지 못할 항목이라 여겨 소홀히 작성했던거 같네요... 이 부분 다시 생각해보고 commit 하겠습니다 🥺

2021-01-21 01:29 UTC, jamessoun93 commented on order/views.py
> +            coupons = UserCoupon.objects.filter(user=user).select_related('user', 'coupon')
select_related / prefetch_related 를 사용하는데에는 정참조, 역참조 관계에서 JOIN 을 해오기 위한 방법 외에 더 중요한 이유가 있습니다. 사실 단순 정참조, 역참조 관계에서 JOIN 쿼리문을 날리기 위해서는 전혀 필요하지 않습니다! 해당 부분 답변 부탁드리겠습니다 :) 너무 중요한 내용이라서요.

2021-01-21 01:35 UTC, jamessoun93 requested changes

2021-01-21 01:35 UTC, jamessoun93 commented on order/views.py
> +                return JsonResponse({"message": "SUCCESS"}, status=200)
흠 여기 flow 를 살펴보면,
- order_address 는 data.get('address') 으로 받아옴으로써 None 이 될 수 있고
- 그 order_address 에 무엇이 저장되었건 user_address 로 치환한 뒤
- order_address 가 None 인 경우 (즉, 기존 user_address 가 NULL 값이었던 경우), 해당 user 의 address 를 None 인 order_address 로 업데이트 시켜준다.

뭔가 이상하지 않나요!?

2021-01-21 01:35 UTC, jamessoun93 commented on user/views.py
> +    @transaction.atomic
회원가입과 동시에 신규가입 쿠폰을 발행하기 위한 transaction 인가요!? 👍👍👍

2021-01-21 01:44 UTC, sue517 commented on order/views.py
> +            coupons = UserCoupon.objects.filter(user=user).select_related('user', 'coupon')
db hit 를 줄이려고 사용하는것 아닌가요...? logging 으로 확인해보았는데 7회에서 5회로 줄어들어서 사용했는데...... 혹시나 다른 이유가 있다면 힌트 좀 주실 수 있을까요ㅠㅠ

2021-01-21 02:35 UTC, lordmyshepherd requested changes

2021-01-21 02:35 UTC, lordmyshepherd commented on order/views.py
> +            coupons = UserCoupon.objects.filter(user=user).select_related('coupon')
정확히는 `Coupon`객체가 아닌 User.Coupon 레코드를 조회하므로, 아래와 같이 수정해주시는게 명확할 것 같습니다.
```suggestion
            user_coupons = UserCoupon.objects.filter(user=user).select_related('coupon')
```

또한, User와 Coupon이 ManyToMany 관계라면, `couponse = user.coupon.all()`로 모든 쿠폰데이터를 가져올 수 있습니다.
이에 맞게 line 131~134를 수정해보시면 가독성이 좋아질 것 같습니다.

2021-01-21 02:35 UTC, lordmyshepherd commented on user/views.py
> +        return JsonResponse({"coupons_list": coupons_list}, status=200)
위와 마찬가지로 수정해주시면 좋을 것 같습니다~

2021-01-21 02:43 UTC, lordmyshepherd requested changes

2021-01-21 02:43 UTC, lordmyshepherd commented on order/views.py
> +            coupons = UserCoupon.objects.filter(user=user).select_related('user', 'coupon')
수아님! 말씀해주신데로 db hit를 줄이려고 사용하는 것이죠~ database에 여러번 조회하는 대신에 한번에 여러 테이블의 데이터를 가져와서 메모리에 캐싱해 놓는 방법이죠. 이 경우에 불필요한 테이블의 데이터까지 join해서 가져올 이유가 있는지 여쭤보시는 것 같습니다. `select_related`를 통해서 `user` 테이블의 데이터를 가져오신 후에 아래 코드에서 사용하고 있지 않는 것 같습니다.
`coupons = UserCoupon.objects.filter(user=user).select_related('user', 'coupon')`

2021-01-21 02:49 UTC, sue517 commented on order/views.py
> +            coupons = UserCoupon.objects.filter(user=user).select_related('user', 'coupon')
@lordmyshepherd 앗 'user' 부분 승현님이 댓글로 얘기해주셔서 지운거 같았는데 안지워졌나보네요...! 다시 지워서 커밋하였습니다!

2021-01-21 02:49 UTC, sue517 commented on order/views.py
> +            coupons = UserCoupon.objects.filter(user=user).select_related('coupon')
확인했습니다 감사합니다~

2021-01-21 02:51 UTC, lordmyshepherd requested changes

2021-01-21 02:51 UTC, lordmyshepherd commented on order/views.py
> +                return JsonResponse({"message": "SUCCESS"}, status=200)
수아님 이부분은 설명해주실 수 있으신가요?

2021-01-21 02:55 UTC, sue517 commented on order/views.py
> +                return JsonResponse({"message": "SUCCESS"}, status=200)
@lordmyshepherd 이 부분 아래와 같이 바꾸어 커밋하였습니다.
user 정보에 address 가 없을 경우 order_address 로 user 정보를 update 하고,
user 정보에 address 가 있는 경우 order address 를 user address로 업데이트 한다는 의미로 만들었습니다.
```
             if user_address is None:
                 User.objects.filter(id=user.id).update(address=order_address)
                 return JsonResponse({"message": "SUCCESS"}, status=200)

             else:
                 order_address = user_address
                 User.object.filter(id=user.id).update(address=order_address)
                 return JsonResponse({"message": "SUCCESS"}, status=200)

```

2021-01-21 08:50 UTC, jamessoun93 commented on order/views.py
> +            coupons = UserCoupon.objects.filter(user=user).select_related('user', 'coupon')
따봉!

2021-01-21 10:22 UTC, merged