[16기 최수아] AGEOSTE-backend Add : user/signupview
wecode-bootcamp-korea/AGEOSTE-backend pull request #5
Opened 2021-01-14 01:14 UTC by sue517

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 view 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 = 아이디
- 이메일에 @ . 포함하는 양식을 갖추도록 정규표현식 사용
- 비밀번호는 8자리 이상, 문자/숫자/특수문자 하나이상은 전부 사용해야 하며 해당 양식 정규표현식 사용
- 중복되는 휴대폰번호 사용 금지. 휴대폰 번호는 010 으로 시작하는 11자 (-포함하지 않음)
- 생년월일은 get 을 사용하여 있을 경우에만 받아올 수 있도록 만들었음

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.) 
pr 작성하다가 오타를 발견하여 push 를 한번 더 진행하였습니다 😣

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-14 06:24 UTC, jamessoun93 requested changes

2021-01-14 06:24 UTC, jamessoun93 commented on user/urls.py
> +from .views import SignupView
정렬해주세요 😉

2021-01-14 06:24 UTC, jamessoun93 commented on user/utils.py
> +def login(func):
함수명은 항상 이 함수가 하는 일을 명확하게 알 수 있는 이름으로 지어주세요!

2021-01-14 06:24 UTC, jamessoun93 commented on user/utils.py
> +            request.user = user
이 부분 완벽하게 이해하고 사용하신건지 궁금하네요..ㅎㅎ 설명타임~?

2021-01-14 06:24 UTC, jamessoun93 commented on user/views.py
> +from my_settings import SECRET
👍👍👍

2021-01-14 06:24 UTC, jamessoun93 commented on user/views.py
> +            if not email or not phone_number or not password or not name:
이 네가지 필드들은 필수값이라서 하나라도 없다면 위에 data['~~~'] 부분에서 KeyError 가 raise 되서 자동으로 except 문으로 넘어가게 됩니다. 따라서 아래에서 KeyError 만 잡아준다면 이 if 문이 필요하지 않게 됩니다~

2021-01-14 06:24 UTC, jamessoun93 commented on user/views.py
> +            if not password_rule.match(password):
validation 메소드들은 전부 한곳에 모아주세요 :)

2021-01-14 06:24 UTC, jamessoun93 commented on user/views.py
> +            return HttpResponse(status=200)
CREATED 니까 200 보다는 201이 더 적합합니다~

2021-01-14 06:24 UTC, jamessoun93 commented on user/views.py
> +        except Exception as e:
Exception 은 이런식으로 전부 잡아주시지 마시고, 구체적으로 어떤 에러가 발생할 수 있는지 확인 후 개별적으로 잡아주세요!

2021-01-14 06:40 UTC, sue517 commented on user/utils.py
> +            request.user = user
제가 이 부분 취약한거 어떻게 아시고 😌... 하지만 이번에는 (조금) 준비되어있습니다...

`token` 에 request headers 부분의 authorization 에 담겨서 오는 token 을 넣어서 그 token 이랑 secret 이랑algorithms='HS256' 을 합쳐서 decode 한걸 `payload` 에 넣고, 거기서 이제 user_id 를 찾아서 request.user 에 넣어준것입니다...!

뭔가 전문적인 용어를 써서 설명하고 싶었는데 그건 안되네요... 이해한대로 적은건데 제대로 잘 설명했을지ㅎㅎㅠㅠ 아무튼 제가 이해한 바는 이렇습니다...!

2021-01-14 06:40 UTC, sue517 commented on user/views.py
> +            if not password_rule.match(password):
회원가입할때 딱 한번 사용하는 method 라고 생각해서 그냥 적었는데 따로 넣는쪽이 좋나요? 궁금합니다!

2021-01-15 02:30 UTC, jamessoun93 commented on user/utils.py
> +            request.user = user
구욷! 완벽합니다!! ㅎㅎ

2021-01-15 02:34 UTC, jamessoun93 requested changes
LGTM 이 머지 않았습니다! 👍

2021-01-15 02:34 UTC, jamessoun93 commented on user/views.py
> +from .validators import ValidationError
이건 굳이 validators.py 를 경유해서 가져오실 필요가 있을까요?

2021-01-15 02:37 UTC, sue517 commented on user/views.py
> +from .validators import ValidationError
앗... 그때 validators.py 에`raise ValidationError` 한 후에 모델에 적용해서 가져올때 써뒀던건데 지우는걸 깜빡했나봐요😂 바로 수정하겠습니다!

2021-01-15 05:01 UTC, jamessoun93 approved these changes
LGTM 수고하셨습니다 👍

2021-01-15 05:01 UTC, merged